spring.application.name=gestor-presupuesto-backend

# 1. Configuración de la Conexión a la BD
spring.datasource.url=jdbc:postgresql://localhost:5432/presupuestodb
spring.datasource.username=user
spring.datasource.password=password

# 2. Configuración de Hibernate/JPA (El ORM)
# 'update' permite que JPA cree o actualice las tablas por ti. ¡MUY ÚTIL AHORA!
spring.jpa.hibernate.ddl-auto=update

# Muestra el SQL generado en la consola
spring.jpa.show-sql=true